PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.pantalla_inicio, name='inicio'),
    path('inicio_sesion/', views.pantalla_inicio_sesion, name='inicio_sesion'),
    path('evento/', views.listar_eventos, name='evento'),
    path('registro/', views.registro, name='registro'),
    path('inscribirse_evento/<int:evento_id>/',views.inscribirse_evento, name='inscribirse_evento'),
    path('perfil_info',views.perfil_usuario, name='perfil_info'),
    
    
]


PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_hotel/urls.py
#urls.py 
from django.contrib import admin
from django.urls import path, include
from evento_app import views  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('evento_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
]

PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/models.py


from django.db import models
from django.contrib.auth.models import AbstractUser,Group,Permission, User

class Usuario(AbstractUser):
    Id_usuario = models.BigAutoField(primary_key=True)
    nombre_usu = models.CharField(max_length=20)
    apellido_usu = models.CharField(max_length=30)
    correo_usu = models.EmailField(max_length=45)
    fechaRegistro_usu = models.DateField(auto_now_add=True)
    groups = models.ManyToManyField(Group, related_name='usuarios')
    user_permissions = models.ManyToManyField(Permission, related_name='usuarios')

class Empleado(models.Model):
    Id_empleado = models.BigAutoField(primary_key=True)
    nombre_emple = models.CharField(max_length=30)
    apellido_emple = models.CharField(max_length=30)
    telef_emple = models.BigIntegerField()
    correo_emple = models.EmailField(max_length=45)
   

class Evento(models.Model):
    nombre_evento = models.CharField(max_length=30)
    fecha_evento = models.DateField()
    lugar_evento = models.CharField(max_length=30)
    descripcion_evento = models.CharField(max_length=100)
    presupuesto_evento = models.BigIntegerField()
    id = models.BigAutoField(primary_key=True)

class EventoEmpleado(models.Model):
    ID_EMPLEADO = models.BigIntegerField()
    ID_EVENTO = models.BigIntegerField()
    fecha_asignacion = models.DateField()
    horario_de_trabajo = models.TimeField()

class Agenda(models.Model):
    Id_evento = models.BigIntegerField()
    fecha_event_agend = models.DateField()
    hora_event_agend = models.TimeField()
    lugar_event_agend = models.CharField(max_length=30)


class Acompanante(models.Model):
    nombre_acomp = models.CharField(max_length=20)
    apellido_acomp = models.CharField(max_length=20)
    dni_acomp = models.BigIntegerField()
    tel_acomp = models.BigIntegerField()
    Id_part = models.BigIntegerField()

class Participante(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name='participantes')
    nombre_part = models.CharField(max_length=20)
    apellido_part = models.CharField(max_length=20)
    tel_part = models.BigIntegerField()
    lugar_procedencia = models.CharField(max_length=30)
    fecha_llegada = models.DateField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre_part} {self.apellido_part} - Evento: {self.evento}"

    class Meta:
        verbose_name_plural = "Participantes"

PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import  Evento

class InicioSesionForm(AuthenticationForm):
    pass



class RegistroEventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['nombre_evento', 'descripcion_evento', 'fecha_evento', 'lugar_evento', 'presupuesto_evento']
        

class FormularioInscripcion(forms.Form):
    nombre = forms.CharField(label='Nombre', max_length=100)
    email = forms.EmailField(label='Correo electrónico')
    telefono = forms.CharField(label='Teléfono', max_length=15)
    lugar_procedencia = forms.CharField(label='Lugar de procedencia', max_length=30)
    fecha_llegada = forms.DateField(label='Fecha de llegada', widget=forms.DateInput(attrs={'type': 'date'}))

PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Evento, Usuario, Participante
from .forms import FormularioInscripcion, RegistroEventoForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from datetime import date
from django.contrib.auth.models import User
from django.db import IntegrityError



def pantalla_inicio(request):
    eventos = Evento.objects.all()
    return render(request, 'inicio.html', {'eventos': eventos})

def pantalla_inicio_sesion(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            # Autentica al usuario
            usuario = authenticate(request, username=username, password=password)

            if usuario is not None:
                login(request, usuario)
                return redirect('evento')
            else:
                messages.error(request, 'Usuario o contraseña incorrectos.')
                return redirect('inicio_sesion')
        else:
            messages.error(request, 'Faltan campos obligatorios en la solicitud.')
            return redirect('inicio_sesion')

    return render(request, 'inicio_sesion.html')

def registro(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        correo = request.POST.get('correo')

        # Validar contraseñas coincidentes
        if password != confirm_password:
            messages.error(request, 'Las contraseñas no coinciden.')
            return render(request, 'registro.html')

        try:
            # Verificar si el nombre de usuario ya existe
            if User.objects.filter(username=username).exists():
                raise ValidationError(_('El nombre de usuario ya está en uso.'), code='existing_username')

            # Obtener la fecha actual
            fecha_registro = date.today()

            # Crear el usuario
            user = User.objects.create_user(username=username, password=password)
            user.first_name = nombre
            user.last_name = apellido
            user.email = correo

            # Asignar la fecha de registro
            user.fechaRegistro_usu = fecha_registro

            user.save()

            # Autenticar al usuario y redirigir a la página de inicio
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, 'Registro exitoso.')
            return redirect('inicio')  # Reemplaza 'nombre_de_la_pagina_de_inicio' con la URL de tu página de inicio

        except ValidationError as e:
            messages.error(request, e.message)

    return render(request, 'registro.html')




def listar_eventos(request):
    eventos = Evento.objects.all()
    return render(request, 'evento.html', {'eventos': eventos})

@login_required
def registrar_evento(request):
    if request.method == 'POST':
        form = RegistroEventoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_eventos')
    else:
        form = RegistroEventoForm()
    return render(request, 'evento.html', {'form': form})




@login_required
def perfil_usuario(request):
    usuario = request.user
    participante = getattr(usuario, 'participante', None)

    context = {'usuario': usuario, 'participante': participante}
    return render(request, 'perfil_info.html', context)


@login_required
def inscribirse_evento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)

    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        tel_part = request.POST.get('tel_part')
        lugar_procedencia = request.POST.get('lugar_procedencia')
        fecha_llegada = request.POST.get('fecha_llegada')

        try:
            participante = Participante.objects.create(
                evento=evento,
                nombre_part=nombre,
                apellido_part=apellido,
                tel_part=tel_part,
                lugar_procedencia=lugar_procedencia,
                fecha_llegada=fecha_llegada,
                usuario=request.user,
            )
            return redirect('inicio')
        
        except IntegrityError as e:
            print(f"Error de integridad: {e}")
            pass

    return render(request, 'formulario_inscripcion.html', {'evento': evento})



PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/templates/evento.html
{% extends "base.html" %}
{% block title %} Evento {% endblock %}
{% block body %}
<div class="container mt-4">
    <h1>Lista de Eventos</h1>
    <ul class="list-group">
        {% for evento in eventos %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-calendar2-event-fill" viewBox="0 0 16 16">
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zM11.5 7a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                </svg> {{ evento.nombre_evento }} - Fecha: {{ evento.fecha_evento }} - Lugar: {{ evento.lugar_evento }} - Descripción: {{ evento.descripcion_evento }} 
            </span>
            <a href="{% url 'inscribirse_evento' evento.id %}" class="btn btn-primary btn-sm me-2">Inscribirse</a>

        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/templates/formulario_inscripcion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscripción a {{ evento.nombre }}</title>
    <link rel="stylesheet" href="{% static 'css/estiloInscrip.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a id="titulo_nave" class="navbar-brand" href="/">SIN Fronteras Eventos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                            <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
                          </svg>    Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'evento' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-calendar2-event-fill" viewBox="0 0 16 16">
                            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zM11.5 7a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                          </svg> Eventos</a>
                    </li>
                  
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                              </svg> Cerrar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'perfil_info'%}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill-check" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm1.679-4.493-1.335 2.226a.75.75 0 0 1-1.174.144l-.774-.773a.5.5 0 0 1 .708-.708l.547.548 1.17-1.951a.5.5 0 1 1 .858.514ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                              </svg>  {{ user.username }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inicio_sesion' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                              </svg> Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registro' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                              </svg> Crear cuenta</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        <h1 class="text-center mb-4">Inscripción a {{ evento.nombre_evento }}</h1>

        <form id="inscripcionForm" method="post" action="{% url 'inscribirse_evento' evento_id=evento.id %}" class="row g-3">
            {% csrf_token %}

            <!-- Campos del participante -->
            <div class="col-md-6">
                <label for="nombre" class="form-label">Nombre:</label>
                <input type="text" class="form-control" name="nombre" id="id_nombre" required>
                <div id="error_nombre" class="text-danger"></div>
            </div>

            <div class="col-md-6">
                <label for="apellido" class="form-label">Apellido:</label>
                <input type="text" class="form-control" name="apellido" id="id_apellido" required>
                <div id="error_apellido" class="text-danger"></div>
            </div>

            <div class="col-md-6">
                <label for="tel_part" class="form-label">Teléfono:</label>
                <input type="text" class="form-control" name="tel_part" id="id_tel_part" required>
                <div id="error_tel_part" class="text-danger"></div>
            </div>

            <div class="col-md-6">
                <label for="lugar_procedencia" class="form-label">Lugar de Procedencia:</label>
                <input type="text" class="form-control" name="lugar_procedencia" id="id_lugar_procedencia" required>
                <div id="error_lugar_procedencia" class="text-danger"></div>
            </div>

            <div class="col-md-6">
                <label for="fecha_llegada" class="form-label">Fecha de Llegada:</label>
                <input type="date" class="form-control" name="fecha_llegada" id="id_fecha_llegada" required>
                <div id="error_fecha_llegada" class="text-danger"></div>
            </div>

            <div class="col-12">
                <button type="button" class="btn btn-primary" onclick="confirmarInscripcion()">Inscribirse</button>
                <a href="javascript:history.back()" class="btn btn-secondary" onclick="return confirmar('¿Estás seguro de que quieres volver atrás?')">Volver Atrás</a>
            </div>
        </form>

        <!-- Área para mostrar el mensaje de aviso y datos del evento -->
        <div id="mensajeAviso" class="mt-4" style="display: none;">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">¡Inscripción Exitosa!</h4>
                <p>Te has inscrito correctamente al evento <strong>{{ evento.nombre_evento }}</strong>. Puedes ver mas informacion sobre tu inscripcion en tu perfil.</p>
                <!-- Puedes agregar más información sobre el evento si es necesario -->
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/confirmarinscripcion.js' %}"></script>
</body>
</html>


PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/templates/inicio.html
{% extends "base.html" %}
{% load static %}


{% block title %} Inicio {% endblock %}

{% block body %}


    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <h1>Información sobre la Empresa</h1>
                <p>
                    La organización SN Fronteras Eventos cuenta con una infraestructura de 4 salones con capacidad para 800 personas, y otros 3 con una capacidad de 250 personas. Las estructuras de estos salones permiten remover las paredes divisorias y formar uno de mayor capacidad. Contando con todas las comodidades tecnológicas de última generación, pantallas gigantes, luces, aire acondicionado, salones acústicos, etc.
                    SN Fronteras Eventos cuenta con un hotel 5 estrellas con una capacidad de 750 habitaciones, y sus instalaciones poseen casino, spa, gimnasio, piscina, helipuerto y playa de estacionamiento. Cuenta con oficinas administrativas, cuya ubicación es el centro de la ciudad, transporte propio desde y hacia el evento (tres combis de 24 asientos cada una) y servicio de catering. De acuerdo a las necesidades, se pueden contratar servicios de terceros como transporte, seguridad, servicios médicos, catering, etc.
                </p>
            </div>
            <div class="col-md-6">
                <h1>Imágenes del Salon</h1>
                <!-- Carrusel de imágenes del hotel -->
                <div id="hotelCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'img/logo.jpg' %}" class="d-block w-100" alt="Salon 1">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'img/imagen2.jpg' %}" class="d-block w-100" alt="Salom 2">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'img/imagen1.jpg' %}" class="d-block w-100" alt="Salom 3">
                        </div>
                        
                    </div>
                    <button class="carousel-control-prev" href="#hotelCarousel" role="button" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" href="#hotelCarousel" role="button" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PROYECTO FINAL- EVENTOS Y HOTEL/evento_hotel/evento_app/templates/inicio_sesion.html
{% extends "base.html" %}
{% block title %} Inicio de Sesión {% endblock %}
{% block body %}
<div class="container mt-4">
    <!-- Muestra mensajes de error si los hay -->
    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 id="titulo_inicio">Iniciar Sesión</h1> <br>
            <form method="post" action="{% url 'inicio_sesion' %}" onsubmit="return validarInicioSesion()">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                        </svg> Usuario</label>
                    <input type="text" name="username" id="username" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                        </svg> Contraseña</label>
                    <input type="password" name="password" id="password" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}
